sudo: required
services:
  - docker

before_install:
  - docker build -t akzuki/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run akzuki/react-test npm run test -- --coverage

after_success:
  - docker build -t akzuki/multi-docker-client ./client
  - docker build -t akzuki/multi-docker-nginx ./nginx
  - docker build -t akzuki/multi-docker-server ./server
  - docker build -t akzuki/multi-docker-worker ./worker
  # Log in to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push akzuki/multi-docker-client
  - docker push akzuki/multi-docker-nginx
  - docker push akzuki/multi-docker-server
  - docker push akzuki/multi-docker-worker

deploy:
  provider: elasticbeanstalk
  region:
  app:
  env:
  bucket_name: 
  bucket_path:
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY